// Generated by Molecule 0.7.0

#define MOLECULEC_VERSION 7000
#define MOLECULE_API_VERSION_MIN 7000

#include "molecule_reader.h"
#include "molecule_builder.h"

#ifndef RC_LOCK_H
#define RC_LOCK_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef MOLECULE_API_DECORATOR
#define __DEFINE_MOLECULE_API_DECORATOR_RC_LOCK
#define MOLECULE_API_DECORATOR
#endif /* MOLECULE_API_DECORATOR */

#include "xudt_rce_mol.h"

/*
 * Reader APIs
 */

MOLECULE_API_DECORATOR  mol_errno       MolReader_SmtProofEntryVecOpt_verify            (const mol_seg_t*, bool);
#define                                 MolReader_SmtProofEntryVecOpt_is_none(s)        mol_option_is_none(s)
MOLECULE_API_DECORATOR  mol_errno       MolReader_RcLockWitnessLock_verify              (const mol_seg_t*, bool);
#define                                 MolReader_RcLockWitnessLock_actual_field_count(s) mol_table_actual_field_count(s)
#define                                 MolReader_RcLockWitnessLock_has_extra_fields(s) mol_table_has_extra_fields(s, 2)
#define                                 MolReader_RcLockWitnessLock_get_signature(s)    mol_table_slice_by_index(s, 0)
#define                                 MolReader_RcLockWitnessLock_get_proofs(s)       mol_table_slice_by_index(s, 1)

/*
 * Builder APIs
 */

#define                                 MolBuilder_SmtProofEntryVecOpt_init(b)          mol_builder_initialize_fixed_size(b, 0)
#define                                 MolBuilder_SmtProofEntryVecOpt_set(b, p, l)     mol_option_builder_set(b, p, l)
#define                                 MolBuilder_SmtProofEntryVecOpt_build(b)         mol_builder_finalize_simple(b)
#define                                 MolBuilder_SmtProofEntryVecOpt_clear(b)         mol_builder_discard(b)
#define                                 MolBuilder_RcLockWitnessLock_init(b)            mol_table_builder_initialize(b, 64, 2)
#define                                 MolBuilder_RcLockWitnessLock_set_signature(b, p, l) mol_table_builder_add(b, 0, p, l)
#define                                 MolBuilder_RcLockWitnessLock_set_proofs(b, p, l) mol_table_builder_add(b, 1, p, l)
MOLECULE_API_DECORATOR  mol_seg_res_t   MolBuilder_RcLockWitnessLock_build              (mol_builder_t);
#define                                 MolBuilder_RcLockWitnessLock_clear(b)           mol_builder_discard(b)

/*
 * Default Value
 */

#define ____ 0x00

MOLECULE_API_DECORATOR const uint8_t MolDefault_SmtProofEntryVecOpt[0] =  {};
MOLECULE_API_DECORATOR const uint8_t MolDefault_RcLockWitnessLock[12] =  {
    0x0c, ____, ____, ____, 0x0c, ____, ____, ____, 0x0c, ____, ____, ____,
};

#undef ____

/*
 * Reader Functions
 */

MOLECULE_API_DECORATOR mol_errno MolReader_SmtProofEntryVecOpt_verify (const mol_seg_t *input, bool compatible) {
    if (input->size != 0) {
        return MolReader_SmtProofEntryVec_verify(input, compatible);
    } else {
        return MOL_OK;
    }
}
MOLECULE_API_DECORATOR mol_errno MolReader_RcLockWitnessLock_verify (const mol_seg_t *input, bool compatible) {
    if (input->size < MOL_NUM_T_SIZE) {
        return MOL_ERR_HEADER;
    }
    uint8_t *ptr = input->ptr;
    mol_num_t total_size = mol_unpack_number(ptr);
    if (input->size != total_size) {
        return MOL_ERR_TOTAL_SIZE;
    }
    if (input->size < MOL_NUM_T_SIZE * 2) {
        return MOL_ERR_HEADER;
    }
    ptr += MOL_NUM_T_SIZE;
    mol_num_t offset = mol_unpack_number(ptr);
    if (offset % 4 > 0 || offset < MOL_NUM_T_SIZE*2) {
        return MOL_ERR_OFFSET;
    }
    mol_num_t field_count = offset / 4 - 1;
    if (field_count < 2) {
        return MOL_ERR_FIELD_COUNT;
    } else if (!compatible && field_count > 2) {
        return MOL_ERR_FIELD_COUNT;
    }
    if (input->size < MOL_NUM_T_SIZE*(field_count+1)){
        return MOL_ERR_HEADER;
    }
    mol_num_t offsets[field_count+1];
    offsets[0] = offset;
    for (mol_num_t i=1; i<field_count; i++) {
        ptr += MOL_NUM_T_SIZE;
        offsets[i] = mol_unpack_number(ptr);
        if (offsets[i-1] > offsets[i]) {
            return MOL_ERR_OFFSET;
        }
    }
    if (offsets[field_count-1] > total_size) {
        return MOL_ERR_OFFSET;
    }
    offsets[field_count] = total_size;
        mol_seg_t inner;
        mol_errno errno;
        inner.ptr = input->ptr + offsets[0];
        inner.size = offsets[1] - offsets[0];
        errno = MolReader_BytesOpt_verify(&inner, compatible);
        if (errno != MOL_OK) {
            return MOL_ERR_DATA;
        }
        inner.ptr = input->ptr + offsets[1];
        inner.size = offsets[2] - offsets[1];
        errno = MolReader_SmtProofEntryVecOpt_verify(&inner, compatible);
        if (errno != MOL_OK) {
            return MOL_ERR_DATA;
        }
    return MOL_OK;
}

/*
 * Builder Functions
 */

MOLECULE_API_DECORATOR mol_seg_res_t MolBuilder_RcLockWitnessLock_build (mol_builder_t builder) {
    mol_seg_res_t res;
    res.errno = MOL_OK;
    mol_num_t offset = 12;
    mol_num_t len;
    res.seg.size = offset;
    len = builder.number_ptr[1];
    res.seg.size += len == 0 ? 0 : len;
    len = builder.number_ptr[3];
    res.seg.size += len == 0 ? 0 : len;
    res.seg.ptr = (uint8_t*)malloc(res.seg.size);
    uint8_t *dst = res.seg.ptr;
    mol_pack_number(dst, &res.seg.size);
    dst += MOL_NUM_T_SIZE;
    mol_pack_number(dst, &offset);
    dst += MOL_NUM_T_SIZE;
    len = builder.number_ptr[1];
    offset += len == 0 ? 0 : len;
    mol_pack_number(dst, &offset);
    dst += MOL_NUM_T_SIZE;
    len = builder.number_ptr[3];
    offset += len == 0 ? 0 : len;
    uint8_t *src = builder.data_ptr;
    len = builder.number_ptr[1];
    if (len == 0) {
        len = 0;
        memcpy(dst, &MolDefault_BytesOpt, len);
    } else {
        mol_num_t of = builder.number_ptr[0];
        memcpy(dst, src+of, len);
    }
    dst += len;
    len = builder.number_ptr[3];
    if (len == 0) {
        len = 0;
        memcpy(dst, &MolDefault_SmtProofEntryVecOpt, len);
    } else {
        mol_num_t of = builder.number_ptr[2];
        memcpy(dst, src+of, len);
    }
    dst += len;
    mol_builder_discard(builder);
    return res;
}

#ifdef __DEFINE_MOLECULE_API_DECORATOR_RC_LOCK
#undef MOLECULE_API_DECORATOR
#undef __DEFINE_MOLECULE_API_DECORATOR_RC_LOCK
#endif /* __DEFINE_MOLECULE_API_DECORATOR_RC_LOCK */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* RC_LOCK_H */
